mysql:
  container_name: dev-ops-rancher-mysql
  image:  dev-ops/mysql-custom:5.7
  volumes:
    - data:/var/lib/mysql
    - mysqld.log:/var/log/mysqld.log
    - my.cnf:/etc/mysql/conf.d/my.cnf
  ports:
    - 3306:3306/tcp
  environment:
    MYSQL_DATABASE: ${mysql_database}
    MYSQL_PASSWORD: ${mysql_password}
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    MYSQL_USER: ${mysql_user}
