version: '3.1'

services:

  mysql:
    image: mysql:5.7.10
    container_name: dev-ops-mysql
    restart: always
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log/mysqld.log:/var/log/mysqld.log"
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'Passpass'

  adminer:
    image: adminer
    restart: always
    ports:
     - 8000:8080
    depends_on:
      - mysql

